### ISSUE TITLE
Nunca había visto declarar una fuenbte en un styled component

### ISSUE THREAD

**Issue by vicenlu** [nyuudo/Thinksigner#3]
Lo suelo hacer en el archivo css principal del proyecto.

Más información:
https://www.positronx.io/react-js-include-custom-fonts-google-fonts-tutorial/

https://github.com/nyuudo/SPRINT-6/blob/d0f01c0ebc8216f0bcc4f0a082b8062d0970fb7f/src/components/Escena.styles.tsx#L9

**Comment by nyuudo** [comment]
Sí, la verdad como lo comentas un lugar centralizado para las fuentes tiene más sentido, ya que es una responsabilidad compartida por muchos más archivos.
