### ISSUE TITLE
Level es demasiado genérica, no coincide con lo que refleja

### ISSUE THREAD

**Issue by vicenlu** [nyuudo/Thinksigner#5]
Se entendería mejor "currentScene", "sceneActive" o algo similar, haciendo referencia a las escenas, más adecuado para el contexto del ejericio.

https://github.com/nyuudo/SPRINT-6/blob/d0f01c0ebc8216f0bcc4f0a082b8062d0970fb7f/src/App.tsx#L12

**Comment by nyuudo** [comment]
Entendido, lo tomaré en cuenta para las nomenclaturas de ahora en adelante (junto con lo que me comentaste de otro STATE que nombré antes), no consideré lo suficiente que el código debe ser leído por otros y mientras más descriptivo al contexto, más fácil entenderlo.
